name: Spawn_at_Random
version: 1.3
main: me.Blackace.spawnatrandom.spawnatrandom
description: A lite plugin that provides random spawns and respawns before players have a bed.
commands:
  randomspawn:
    description: Forces a random spawn on target player and logs the new location to the Spawns.yml file. REQUIRES a player name.